language: python
python:
  - "2.7"
before_install:
  - source ./scripts/ci/setup_env_hemlock_rest.sh
  - sudo apt-get update -qq
install:
  - pip install pexpect --use-mirrors
  - pip install web.py --use-mirrors
  - pip install hemlock --use-mirrors
  - pip install pytest --use-mirrors
  - pip install pytest-cov --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install hemlock-rest --use-mirrors
before_script:
  - py.test --cov=hemlock_rest
script: py.test -v --cov hemlock_rest --cov-report term-missing
after_success:
  - coveralls
branches:
  except:
  - gh-pages
notifications:
  email:
    - charliel@lab41.org
